#!/usr/bin/env groovy


node {

    stage('checkout'){
        checkout scm
    }

    withCredentials([[
        $class : "UsernamePasswordMultiBinding",
        credentialsId: 'dockercreds',
        passwordVariable: 'GITHUB_PASSWORD',
        usernameVariable: 'GITHUB_USERNAME'
    ]]){
        stage('build docker'){

            sh """

                   CONTAINER_ID=\$(docker-compose -f docker-compose.yml build)
                   echo "Container id: \${CONTAINER_ID}"
                   docker container ls --all
                   docker image list
                   echo "\${GITHUB_PASSWORD} | docker login --username="\${GITHUB_USERNAME} --email=will.rubel@gmail.com --password-stdin
                   docker tag "\${CONTAINER_ID}" rubelw/mymoto:latest
                   docker push rubelw/mymoto
                """
        }
    }


    stage('clean-up workspace'){
        step([$class: 'WsCleanup'])
    }

}