#!/usr/bin/env groovy


node {

    stage('checkout'){
        checkout scm
    }

    withCredentials([[
        $class : "UsernamePasswordMultiBinding",
        credentialsId: 'dockercreds',
        passwordVariable: 'GITHUB_PASSWORD',
        usernameVariable: 'GITHUB_USERNAME'
    ]]){
        stage('build docker'){

            sh """

                   docker-compose -f docker-compose.yml build
                   docker container ls --all
                   docker image list
                   CONTAINER_ID=\$(docker images | grep 'moto\s*latest' | awk '{print \$3}')
                   echo "Container id: \${CONTAINER_ID}"
                   echo "\${GITHUB_PASSWORD}" | docker login --username="\${GITHUB_USERNAME} --email=will.rubel@gmail.com --password-stdin
                   docker tag "\${CONTAINER_ID}" rubelw/mymoto
                   docker push rubelw/mymoto
                """
        }
    }


    stage('clean-up workspace'){
        step([$class: 'WsCleanup'])
    }

}