#!/usr/bin/env groovy


node {

    stage('checkout'){
        checkout scm
    }

    stage('build docker'){

        sh """

               docker-compose -f docker-compose.yml build
               docker container ls --all
               docker image list
            """
    }

    stage('clean-up workspace'){
        step([$class: 'WsCleanup'])
    }

}